### PR TITLE
Filename pattern

### PR DESCRIPTION
**Pull request by adam-abed-abud**
Merged the latest changes which are on `develop`.
Added both event and fragment based writing modes.
`SimpleDiskWriter` is failing for the moment, I'm currently working on the fix.

### CODE REVIEW

**Comment by bieryAtFnal** [comment]
Looks good - I was able to build and run the BinaryWriter.

I'll look into some more details later, but I wanted to send a quick note with one request that I'd like you to think about.  I'd like the BinaryWriter DAQModule (and any similar DAQModules that someone might write) to be be even simpler than what it is now.  I'd like it to be able to create a single HDF5DataStore instance in BinaryWriter and use that one instance to write all of the fragments in whatever files are configured.

**Comment by bieryAtFnal** [comment]
I've made a couple of changes on the `filenamePattern` branch.

1. I was very surprised that the HDF5DataStore class wasn't already making used of the InvalidHDF5Group ERS Issue.  I remember that Adam showed me this code earlier today, and it looked fine.  In any case, I found that the code on the `filenamePattern` branch didn't seem to be making use of it, so I added it in.  Please check that what I did is correct.  And, if I missed an existing change to do that, feel free to revert my change.

1. I added some unit tests that will hopefully demonstrate the interface that I would like to see in the HDF5DataStore constructor, with regards to my earlier comment about a single HDF5DataStore instance to write all of the files.  In the `unittest/HDF5Write_test.cpp` file, there are unit tests that expect multiple files to be written by a single HDF5DataStore instance.  I've commented out the "build" line for this unit test in CMakeLists.txt, but I want us to work toward getting the unit tests to work _as written_.

**Comment by bieryAtFnal** [comment]
Sorry, I should have said that the first issue in my previous post is something that is something that I'd like us to work out as part of this PR (and that should be easy).  

But, the second issue can/should wait until later.  I just wanted to make those unit tests available to help demonstrate the 'one instance can write many files' model.

**Comment by bieryAtFnal** [comment]
I'm not sure that this is the best place (or best branch) to have added this, but I've created an HDF5WriteAndRead_test.cpp unit test on the `filenamePattern` branch.

This unit test is definitely beyond the scope of this Pull Request, but my sense is that it will be helpful to have draft unit tests that will help us talk about the expected behavior of the HDF5DataStore methods in a consistent way.  And, my sense is that making this available sooner rather than later will be valuable.

I have not tried to compile the HDF5WriteAndRead unit test, and I expect that there will be some things that need to be fixed.  But, I hope that the expected behavior is clear from looking at the tests.
For reference, there are four tests.  Two that deal with fragment-based files, and two that deal with event-based files.  In  a different 'test' dimension, there are two test that write the data using one DataStore instance and read it back with another DataStore instance, and two tests that write and read the data using the same DataStore instance for both operations.

**Comment by carloschavez** [comment]
Hello,
I tried compiling the HDF5WriteAndRead unit test that Kurt prepared,  and the first thing that complains was about the constructor of HDF5DataStore.  The constructor now requires more parameter to accommodate for the operational_mode option. This breaks HDF5WriteAndRead as Kurt was assuming to use the old constructor of HDF5DataStore. 

Im thinking that it would be nice to have a default operational mode, lets say "one-event-per-file", and have two constructors,  one that requires this operational_mode parameter, and the another that does not require and assumes the default option ?

It is just a thought,  as I can already see some reasons why it would be clearer to have explicit parameter in the constructor.

**Comment by bieryAtFnal** [comment]
Hi Carlos,
As I mentioned in an earlier post, I did not expect that HDF5WriteAndRead_test.cpp would compile at this time.

However, that is not because I used an old constructor for HDF5DataStore, but rather that I used one that doesn't exist yet.

Unless I am forgetting something, the HDF5DataStore constructor should accept the following arguments:
  // - name of the data store (just a descriptive name)                                                                                     
  // - directory path where the files should be stored and/or read from                                                       
  // - filename prefix                                                                                                        
  // - file "mode"

We could provide a default value for fileMode, but that is a secondary issue, in my opinion.  The bigger issue is getting a constructor that does not accept the EventID and the GeoLocation.

**Comment by bieryAtFnal** [comment]
To be clear, none of these "extra" commits that I've added to the `filenamePattern` branch should break its build, since I haven't added any of them to the CMakeLists.txt file.

**Comment by bieryAtFnal** [comment]
Very cool!  I've looked at the code and run the binary writer (using binary_writer_demo.json) and enabled the HDF5Write_test unit test, and everything looks quite good.  Thanks, Adam, for making the changes.

In addition to enabling the HDF5Write_test unit test (in the CMakeLists.txt file), I added a unit test to that file for the "all-per-file" operationMode.  All of the unit tests pass.  (I committed these code changes to the `filenamePattern` branch and pushed those commits to the central repo.  These commits didn't change any of the files that Adam changed; they were just the extras for the unit test.)

One issue that I noticed is that the `filePtr` is not deleted at the end of the `write()` method (the HighFive::File instance that it points to is created with a call to `new`).  We should add that `delete filePtr` line so that we don't leak memory and so that the HighFive::File destructor is called in a timely way for our filePtrs.
My sense is that we should fix this before a merge to the `develop` branch, and once this change is made, I'm fine with a merge to `develop`.

Carlos, once you have looked at the code, confirmed that the `delete` call was added, and are comfortable approving this PR, please feel free to merge the branch to develop.

**Comment by adam-abed-abud** [comment]
I added the deletion of the filePtr.

Carlos, please have a look whenever you can.

Thanks!

**Comment by carloschavez** [comment]
Hi Adam,  this all look very good.
I am merging the code into develop branch right now.

**Pull request merged**
