### PR TITLE
Feature/combiner app

### PR DESCRIPTION
**Pull request by bieryAtFnal**
This pull request is for code changes on the _feature/CombinerApp_ which were made to get the data_generator_demo and data_combiner_demo apps to work.

The instructions for testing these changes are on the [Validating the deliverables from Sprint 2](https://github.com/DUNE-DAQ/ddpdemo/wiki/Validating-the-deliverables-from-Sprint-2) WIki page, with the caveat that you will need to check out the _feature/CombinerApp_ branch after cloning the _ddpdemo_ repo.

### CODE REVIEW

**Comment by carloschavez** [comment]
I noticed some variable names  in the json files are not consistent, for example  variable sleepMsecWhileRunning is different to all the other configuration variables in data_combiner_demo.json .

**Comment by carloschavez** [comment]
I  am happy with the changes,  I did run some tests  and all worked well  : data_generator and data_combiner.
My previous comment on the variables  should not stop  the merge.
Adam, I leave it to you to make the merge when you have had a look.

**Comment by bieryAtFnal** [comment]
Thanks Carlos, I will make a note about those JSON parameter names.

**Comment by adam-abed-abud** [comment]
General question: now that we have the `DataGenerator`, what is the point in keeping also the `BinaryWriter` ? 

Other than that I'm happy to merge.

**Comment by bieryAtFnal** [comment]
Yes, it makes sense to remove BinaryWriter.  I've done that and pushed the changes to the central repo.

**Comment by adam-abed-abud** [comment]
Fantastic, thanks Kurt. 
Adding the updated README file and merging the branch with `develop`.

**Pull request merged**
