### PR TITLE
Feature/unit test cleanup

### PR DESCRIPTION
**Pull request by bieryAtFnal**
This is a draft pull request to give everyone a chance to look at the "void*" changes that I am proposing.

These changes are on the feature/UnitTestCleanup branch, and they can be view using the following link:  [https://github.com/DUNE-DAQ/ddpdemo/commit/16f28d727b99841575ed58756b9439058e7ee55e](https://github.com/DUNE-DAQ/ddpdemo/commit/16f28d727b99841575ed58756b9439058e7ee55e)

Please note that there are some additional changes on that branch.  The full set of changes include:
* a change to disk_writer_demo.json to have it put all of the data that is written in the DiskWriterDemo in one file.  This is to match the behavior that we had in this demo at the end of Sprint 1.
* some StorageKey unit tests were added.
* the void* changes were added (more information below)
* a KeyedDataStore_test unit test was added

With the void* changes,
* I made the change that we discussed to use `new char[size]` instead of `malloc(size)` in HDF5DataStore::read()
* I left the type of the KeyedDataBlock::owned_data_start variable as std::unique_ptr<char>.  There are complications with changing it to std::unique_ptr<void> that we can talk about later.  Also, this variable is somewhat of a private data member in KeyedDataBlock, so I felt that its type can be a little more flexible.  (Yes, I know that this var is not strictly private, but it probably will be soon.)
* I modified the type of the KeyedDataBlock::unowned_data_start variable and the KeyedDataBlock::getDataStart() method to be void*.  This is in ilne with our goal to move to a void* interface.

For future reference, here are a couple of useful links:
* for creating a custom deleter for std::unique_ptr<void>:  [https://stackoverflow.com/questions/39288891/why-is-shared-ptrvoid-legal-while-unique-ptrvoid-is-ill-formed](https://stackoverflow.com/questions/39288891/why-is-shared-ptrvoid-legal-while-unique-ptrvoid-is-ill-formed)
* for handling Linux signals in Boost unit tests:  [https://stackoverflow.com/questions/41976686/can-i-install-a-signal-handler-for-boost-unit-tests](https://stackoverflow.com/questions/41976686/can-i-install-a-signal-handler-for-boost-unit-tests)
* for Boost unit test: [https://www.boost.org/doc/libs/1_66_0/libs/test/doc/html/boost_test/utf_reference/testing_tool_ref.html](https://www.boost.org/doc/libs/1_66_0/libs/test/doc/html/boost_test/utf_reference/testing_tool_ref.html)

### CODE REVIEW

**Comment by bieryAtFnal** [comment]
I should have said that I created the `feature/UnitTestCleanup` branch from the `feature/CombinerApp` branch, so it has all of the changes from there.  This means that it is as up-to-date as possible.

**Comment by bieryAtFnal** [comment]
It may also be useful to look at the KeyedDataBlock unit test that was included in a separate commit (link: [https://github.com/DUNE-DAQ/ddpdemo/commit/aabefc531ee4249f9d1caaf32afb225c640bd5b9](https://github.com/DUNE-DAQ/ddpdemo/commit/aabefc531ee4249f9d1caaf32afb225c640bd5b9) )

**Comment by bieryAtFnal** [comment]
Since Pull Request #42 is looking good, I'm going to convert this draft PR into a normal one.

Once _feature/CombinerApp_ is merged to develop, I believe that this PR is ready for people to review it.

**Comment by adam-abed-abud** [comment]
Hi Kurt,

I'm very happy with this PR.

I noticed that all char* have been changed to void* and that works fine.

The unit test "KeyedDataBlock_test.cxx" is very interesting and works fine. However, I noticed that the test "LocalBufferOwnership" test is missing some checks. Maybe we can add a BOOST_REQUIRE_EQUAL like for the test "SimpleLocalBuffer". What do you think?

**Comment by bieryAtFnal** [comment]
Hi Adam,
Sure, that sounds good.  I copied tests from SimpleLocalBuffer, like you suggested, and I took one from TransferredBufferOwnership.  Please take a look and let us know if the changes are along the lines of what you were thinking.

**Comment by adam-abed-abud** [comment]
That's perfect, thanks!

I will leave the merge to Carlos if he has any comments to add.

**Pull request merged**
