### PR TITLE
Hdf5 data store

### PR DESCRIPTION
**Pull request by adam-abed-abud**

### CODE REVIEW

**Comment by bieryAtFnal** [comment]
I ran some tests and looked at the code changes, and in general, everything looks good.

A few comments/questions:

- It looks like the `binary_writer_demo.json` file configures the app to write 10 fragments per event, but I only see 9 fragments in each of the 5 data files.  Is there some subtlety that I'm missing?

- Could we put back the build lines for `SimpleDiskWriter.cpp` in the `CMakeLists.txt` file so that we get both SimpleDiskWriter and BinaryWriter DAQModules?

- I'm curious why the type of the `owned_data_start` field in KeyedDataBlock was changed from a unique_ptr to a shared_ptr.

Thanks!

**Comment by adam-abed-abud** [comment]
Hi Kurt! 

Good catch in the `owned_data_start` field. I had previously changed it to a shared_ptr for some debugging and left it since then. I checked and it works with unique_ptr. 

I also changed the `CMakeLists.txt` file in order to build the SimpleDiskWriter. Can you please check if it works? 

Regarding the 9 out of 10 fragments, I noticed that the first kilobytes are empty but that is the metadata of the HDF5 file I guess. I will investigate further.

**Comment by bieryAtFnal** [comment]
Thanks for the fixes.  A few more things that I noticed:

- It would be good to "install" the BinaryWriter and its JSON file.  This is done with extra statements in the CMakeLists.txt file, as shown in `/afs/cern.ch/work/b/biery/public/dunedaq/adamTest/sourcecode/ddpdemo/CMakeLists.txt`

- I noticed that the SimpleDiskWriter now creates a file called `demo.hdf5.hdf5`.  We should either fix `test/disk_writer_demo.json` to not specify the `hdf5` file extension, or change to code back to not append that.  Something to consider is whether we want to force users to use the `hdf5` extension.  If we hard-code that in the code, then we will be forcing them to use it.

- I noticed that when I give the `stop` command to the BinaryWriterDemo, it throws an unknown exception.  And, when I give it the `quit` command, the app core dumps.  Do you also see this?

**Comment by adam-abed-abud** [comment]
I updated the CMakeLists file, thanks! 

I think we have to force the use of the `.hdf5` extension if you are using the HDF5DataStore. This is because in my opinion the goal is to have HDF5 files. I imagine that in the future we will have other implementations of the DataStore and then we can have other extensions. If we are going for this direction then I suggest we remove the .hdf5 extension in the `test/disk_writer_demo.json`. Let me know what you think so then we can update the `json` file or the code.

Regarding the stop and quit, I never investigated it to be honest. I imagine we might need something like "close" file or even use the HDF5 `flush()` when the stop data taking is issued. Do you have any ideas?

**Comment by bieryAtFnal** [comment]
Sounds good, I'll (re)confirm the CMakeLists.txt.

Regarding the file extension, my tendency is to give users control.  I'll run a test to see if tools like `h5dump` require an hdf5 extension or not, and let you know.  This is not a big deal to me, but my honest answer is that I'd vote for not hard-coding it (if my tests show that tools don't require a specific extension).  But, I'm fine with doing that, for now, if you feel strongly.

Regarding the crash...  I noticed that the do_work method is exiting before the `stop` command is typed in.  I'll try to take a look and see if that is part of the problem.  Maybe something in the code is expecting it to still be running later in the program.

**Comment by bieryAtFnal** [comment]
Another comment on the directoryPath and filenamePattern that we pass into the HDF5DataStore constructor...

I believe that we currently expect users to supply a trailing slash in the directoryPath (e.g "/tmp/").  Forgetting it seems like a mistake that some fraction of users are likely to make.  (Without knowing that the trailing slash is needed, I would naturally just specify "/tmp".)

Whenever I'm developing tools like this, I like to make them as easy to use as possible for the user.  In this case, I would equate "easy" with being able to specify "/tmp" or "/tmp/" and have both of them work.  

So, we should consider whether to allow directoryPaths with, and without, a trailing slash.

**Comment by carloschavez** [comment]
Should we go ahead with the Merge or should we wait until the /tmp issue raised by Kurt be addressed in this branch ?

**Comment by bieryAtFnal** [comment]
I'd like to, at least, look at the crash before we merge...

**Comment by carloschavez** [comment]
That is right,  sorry I forgot about that slight issue

**Comment by bieryAtFnal** [comment]
I tested h5dump and HDFView on a file named "hi.bye" (renamed from demo_event_4.hdf5), and both tools were able to successfully read the file.  So, it doesn't seem that an "hdf5" file extension is required.

I found that adding a sleep() loop in the BinaryWriter::do_work() method helped avoid the crash.  The modified code is here:  /afs/cern.ch/work/b/biery/public/dunedaq/adamTest/sourcecode/ddpdemo/src/BinaryWriter.cpp

Adam, I understand your desire to write out the data and exit.  So far, though, we've been developing DAQModules, which expect a certain state behavior (e.g. doing work while in the running state).  I've made a note to think about how we should be implementing apps that don't really need state behavior.  In the meantime, maybe we just add a sleep() loop to BinaryWriter::do_work().

**Comment by adam-abed-abud** [comment]
Hi Kurt! 

Thanks for fixing this issue, I pushed your fix to the branch. For now we can keep it like this but we will need to adjust it later. 

I will fix the trailing slash in the directory paths now.

**Comment by bieryAtFnal** [comment]
I've fetched the latest code and run some tests.  Two comments:

- I noticed that the trailing slash code was added to both BinaryWriter.cpp and SimpleDiskWriter.cpp.  Why not simply add it to HDF5DataStore.cpp.  A one-character change to the following line would fix it for all users, n'est pas?
  - `filePtr = new HighFive::File(path + "/" + fileName + ".hdf5", HighFive::File::OpenOrCreate | HighFive::File::Truncate);`

- The SimpleDiskWriter now seems to be writing an empty file (this must be the issue that Carlos noticed).  I haven't investigated this yet, but I will.

I think that we should talk about and/or fix the first issue.  The second one could wait until a later Pull Request, if we want.

**Comment by adam-abed-abud** [comment]
You are right! That's a more elegant way of fixing the issue. I pushed the fix to the `HDF5DataStore.cpp` file.

**Comment by bieryAtFnal** [comment]
Great!  Thanks.
I'll approve this Pull Request and merge the code changes to _develop_.

**Pull request merged**
