### PR TITLE
Feature/issue26 data store reader

### PR DESCRIPTION
**Pull request by carloschavez**
Here is the summary of my PR:
Added yet another module : ddpdemo_SimpleDiskReader_duneDAQModule
That takes test/disk_reader_demo.json in the usual way and reads a file specified in the usual path and reads a single fragment give by a StorageKey  (for testing this key can be configured in the json file)
The reading method is implemented in HDF5DataReader.hpp &  HDF5DataReader.cpp
This will need to be merged with HDF5DataStorage.xpp  in the future, but for now while developing the other reading methods I will leave it not merged yet.

### CODE REVIEW

**Comment by bieryAtFnal** [comment]
Hi Carlos,
This looks good to me.  I ran the disk_reader_demo.json file and confirmed that it works as expected.  (I changed the eventId and geoLocation config params a couple of times and re-ran the test, just for fun.)

Looking at the code, there were only a couple of things that I noticed:

- the variable "thedataSpace" doesn't seem to be used after being initialized in HDF5DataReader::read().  This is not a big deal, and looking into why it is there can be part of later work.  I was just surprised that the compiler didn't yell about an unused variable.

- the use of InvalidDataReaderError in HDF5DataReader::read().  This Error class is defined in our "src" classes, and would be more appropriately defined in the HDF5DataReader class.  Also, a better name might be something like InvalidGroupError.  This is analogous to a similar issue in Adam's write() changes.  I will file a GitHub issue with some suggestions for this.

I'm willing to approve this request and merge the code to the `develop` branch, but I'll give Adam a chance to review and comment first.

**Comment by adam-abed-abud** [comment]
Hi! 
This PR looks good to me as well. I checked it out and it works on my side. 
I think for now we should keep the reader and the writer separate. We can merge them at the end of the sprint.

**Comment by bieryAtFnal** [comment]
Thanks Adam,
I will merge this code to `develop`.  I will try to do it in a way that doesn't delete the branch, but I need to figure out how to do that in GitHub.
I'd like us to merge the read and write functionality sooner than the end of the Sprint.  We'll watch for a good time, based on other changes that we want to make.  
There will be cleanup tasks, like converting the interface to use void* (while keeping the HDF5 DataSets using a non-void type), that we will need to do after everything settles down, so it will be great for things to settle down before the last couple of days.

**Comment by carloschavez** [comment]
Thanks Adam and Kurt,
I will take care of the points that Kurt mention in his first post,  probably in another branch but I will make sure they are not forgotten.

**Pull request merged**
