### PR TITLE
Conforming with v1.2.1

### PR DESCRIPTION
**Pull request by mroda88**
Hi all, this is a minimal code that brings ddpdemo in alignment with the latest daq-buildtools and appfwk. 

With respect to the chat we had an hour ago I realised a problem. 
Until the factory is implemented we cannot have the `DataStore`s as plugins or they won't be loaded in runtime as the share object library will not be linked. 
So I moved them in `src`. Even if the files are in src, the corresponding headers are not in `include` to make clear what should be the "long term" future for those file.

### CODE REVIEW

**Comment by bieryAtFnal** [comment]
Hi Marco,
Here are my comments and questions from looking at the code on the _MarcoAttempt_ branch...
- I was able to build the package in a v1.2.1-based software environment, as expected.  And, the unit tests all worked, which is great.
- I  noticed that the `find_dependency` call in `ddpdemoConfig.cmake.in` changed from requesting _appfwk_ to _HighFive_.  Did the dependence on _appfwk_ go away somehow, or is it automatically handled somehow?
- Is it typical to `#include` header files from the _src_ subdir using "../src/blah.hpp" (for example, in our unit tests; I'm mainly curious about the "../")?  Surprisingly, I didn't find an example of other packages putting headers in _src_.  I expect that some of them will..
- The differences between new and old files all looked good, of course helped by the introduction that you provided yesterday when we all talked.
- Thinking ahead to whether HDF5KeyTranslator, etc. moves to the _plugin_ subdirectory later...  If we create a couple of different libraries from the code in the _src_ subdir, e.g. one for HDF5-related stuff and one for other stuff, would that help with the library-loading niceness that you described yesterday?

Thanks,
Kurt

**Comment by mroda88** [comment]
Hi Kurt, 
I'll answer here but then we can discuss it again on slack or on tuesday. 

> I noticed that the find_dependency call in ddpdemoConfig.cmake.in changed from requesting appfwk to HighFive. Did the dependence on appfwk go away somehow, or is it automatically handled somehow?

Good catch. For sure our package depends on HighFive. About appfwk I was not sure. Following the [toylibrary](https://github.com/DUNE-DAQ/daq-buildtools/blob/develop/toylibrary/cmake/toylibraryConfig.cmake.in) example by John, I see his library is only listing the other dependencies. Probably it is a good idea to add appfwk as well. Shall I add it to this PR directly?

> Is it typical to #include header files from the src subdir using "../src/blah.hpp" (for example, in our unit tests; I'm mainly curious about the "../")? Surprisingly, I didn't find an example of other packages putting headers in src. I expect that some of them will..

This I was a bit undecided as well. It is certainly not typical and I didn't like it. But let me try to explain what I noticed and the problem I had to face. Sorry it's complicated and long. I'll use the example of `DataGenerator` as an example, to point to specific files.
Normally I would have simply written
```c++
#include "HDF5DataStore.hpp" 
```
completely position independent. The problem arises from the fact that DataGenerator.cpp is in plugins directory now and HDF5DataStore.hpp is in src, so the position indepent header is not working because only include and the local directory are added. 
It used to be in include, but in the long run it cannot stay there as it is not part of the public headers. So now is in src as it's the piece of code that is compiled for the actual implementation for HDF5DataStore. 
In the future (maybe even next week), when we have proper factory, this include will disappear completely in favour of the generic 
```c++
#include "ddpdemo/DataStore.hpp"
```
On top of this issues, there is something I noticed in appfwk which is what is confusing me. 
We are forced to do this because `DataGenerator` now has to be in plugin or it's throwing a compile error in the new system. 
But in appfwk/develop the plugins are in src! and so they don't have to do this when headers are connected. I don't know how they manged it. 
My suggestion for this item is to wait until we have our factory in place and the ugliness will disappear naturally. 
If we need it to fix it earlier, probably John will  be able to tell us how to replicate the trick in appfwk.

> Thinking ahead to whether HDF5KeyTranslator, etc. moves to the plugin subdirectory later... If we create a couple of different libraries from the code in the src subdir, e.g. one for HDF5-related stuff and one for other stuff, would that help with the library-loading niceness that you described yesterday?

Yes, this will make all very clean. 
I hope it's clear. Otherwise please ask. 

Marco

**Comment by mroda88** [comment]
Actually, I thought a bit more. Not all the ugliness will disappear once we have the factory. The tests are very specific, there probably the ugliness will never go away. But we can probably write tests which are less specific to headers that are not public.

**Comment by bieryAtFnal** [comment]
Thank you for your replies.

I'm fine with changing the ddpdemoConfig.cmake.in file on the _MarcoAttempt_ branch to have the find of the _appfwk_ package...

I, too, suspect that some amount of ugliness won't go away regarding the inclusion of header files from the _src_ directory.  And, I suspect that we will need to talk with other DAQ Consortium colleagues about the right way to handle this.  I say this both because you noticed surprising things in what the _appfwk_ package is currently doing, and because I'm not certain where to put the Nljs.hpp and Struct.hpp files that we generate from our internal schemas.  (Also, I believe that these files will provide even more test cases of how granular we want to make the libraries that we generate in ddpdemo.)

Switching topics, a bit...
I created a new branch (_DBTandCodeGenUpdates_) from the _MarcoAttempt_ branch and added some code-generation files.  In order to get the `DataGeneratorDemo` to work, I needed to make a couple of small changes to _plugins/DataGenerator.*._  I committed the generated Nljs.hpp and Struct.hpp files to _include/ddpdemo/datagen_, even though I think that they should go underneath _src_ in the medium term.  For now, though, it was easier to just put them under the _include_ directory so they would naturally be found during the build.
There are instructions at the bottom of the [v1.2.1 Notes](https://github.com/DUNE-DAQ/ddpdemo/wiki/Notes-on-conversion-to-DAQ-Suite-v1.2.1) Wiki page that describe how to build and run the (mostly) updated data_generator_demo.  Remaining work might be to update the handling of the configuration parameters in DataGenerator.cpp.

**Comment by bieryAtFnal** [comment]
By the way, what is the daq-buildtools command for building a second and third library in a package?  The comments with daq_add_library say that it creates the main library for a package.  That's fine, but what we we want more than one?

**Comment by mroda88** [comment]
At the moment there is no another command: the library is one for every package. But every plugin will have its own library. So effectively, in the context of shared object libraries, every plugin will generate another library. but plugins libraries are not linked in the same ways that libraries are, so they are no equivalent.

**Comment by bieryAtFnal** [comment]
As we've discussed in recent meetings, we are all comfortable with these changes, so I will close this pull request and merge the code on the MarcoAttempt branch to _develop_.

**Pull request merged**
