### PR TITLE
Feature/hdf5 key translator

### PR DESCRIPTION
**Pull request by bieryAtFnal**
This Pull Request is for the code changes on the HDF5_key_translator branch.

These changes are the addition of a class to manage the translation between StorageKeys and HDF5 'paths'.

The verification of this code will likely include looking at the new header file, looking at the associated unit test, and confirming that the unit tests pass (using `./build_daq_software.sh --pkgname ddpdemo --unittest`.

### CODE REVIEW

**Comment by carloschavez** [comment]
Hi Kurt 
This all look very good. 
I was wondering if the reason why these methods belong to a class  is only to wrap them together and tag them with a version. 

In a wider context where we want to add other utility methods to the package ,  we will have to create new clases for these new methods . Here I'm thinking about methods that have nothing to do with keys and hdf5  paths. 

Anyway I could not find anything wrongn your code or that I could suggest to improve it. 
I tested your changes and played around with the unit tests ,  and  all works well and as expected. 

I'm happy to  merge the branch. 
I will leave it to Adam to do it

**Comment by bieryAtFnal** [comment]
Hi Carlos,
Yes, the only reason why I made HDF5KeyTranslator a class was to put the "current version" field in a private data member.  Thinking about it now, it seems quite reasonable to make CURRENT_VERSION a public constant, in which case we could make all of the methods functions within the HDF5KeyTranslator namespace. 

A different model (functions within a namespace) is what I used for [HDF5FileUtils.hpp](https://github.com/DUNE-DAQ/ddpdemo/blob/feature/Issue24_getAllKeys/include/ddpdemo/HDF5FileUtils.hpp).  This is a file where I've grouped some functions that I'll need for `getAllExistingKeys()`.  It will be part of my next PullRequest.

I've only thought a little bit about additional functions that we will want (where to put them).  The other day, the three of us talked about a utility method that takes the relevant information and creates the fully-specified file path+name for us.  Initially, I was thinking that this new function could to into HDF5FIleUtils.hpp, but now I wonder if it should go into HDF5KeyTranslator.  The "KeyTranslator" name could encompass translation to HDF5 internal Group/DataSet paths and HDF5 filenames.  I think that it would be nice to be able to have one file where we need to change things when we add new fields to StorageKey and want to update our translation routines to take advantage of them.

I'm not sure if this answers your question about other utility methods and classes for them, but I hope that it helps.
Kurt

**Comment by adam-abed-abud** [comment]
Hi Kurt,

I'm going to merge this branch with `develop`. 

It works fine on my side. I tried to "break" it but it is sufficiently robust. 

Regarding what to do when we will have other versions, I think it is a problem that we will also face when we will change the structure of the key. Let's keep it in mind.

**Comment by carloschavez** [comment]
Hi Kurt,  
Thanks very much for the answer and explanations, it really helps me to understand the thinking behind it.
Thanks for taking the time to write it detail.

**Pull request merged**
