### PR TITLE
feature/MoreUnitTestCleanup

### PR DESCRIPTION
**Pull request by bieryAtFnal**
This branch actually has more unit test cleanup that the feature/UnitTestCleanup branch, and this Pull Request is to describe the changes on the feature/MoreUnitTestCleanup branch and ask for approval for those changes.

The changes include:

- the addition of an HDF5Combiner unit test
- renaming of HDF5WriteAndRead_test to HDF5Read_test
- removal of obsolete comments and unneeded code from unit tests
- conversion of some ERS_INFO messages in HDF5DataStore to TLOG(TLVL_DEBUG) to reduce the amount of console output during unit tests (and running of our demos).  Please check if this is OK.
- update of the HDF5DataStore::getAllFiles_() method to use HDF5FileUtils::getFilesMatchingPattern
- changes of JSON config param names from camel-case to lower-case with underscores
- a change to SimpleDiskReader to only do one read in do_work()

### CODE REVIEW

**Comment by adam-abed-abud** [comment]
Hi Kurt, 

I looked at your code. I checked line by line all the changes and they worked fine. 

I don't understand this line (L138) in the HDF5Combiner_test. Can you please comment on what you want to test there?
```
BOOST_REQUIRE_CLOSE_FRACTION(
    static_cast<float>(singleFileSize), static_cast<float>(EVENT_COUNT * GEOLOC_COUNT * DUMMYDATA_SIZE), 0.15)
```

The following is a comment for the next sprint. I believe that having all the output in the logs and not in the console does not give the user the impression that the application is running. I agree that before there were a lot of ERS messages. I suggest we keep the Trace messages as it is now but we might need to include some (reduced?) messages for the next sprint.

**Comment by bieryAtFnal** [comment]
Hi Adam,
Thanks for taking a look and for sending your feedback and question.

The [BOOST_REQUIRE_CLOSE_FRACTION](https://www.boost.org/doc/libs/1_74_0/libs/test/doc/html/boost_test/utf_reference/testing_tool_ref/assertion_boost_level_close_fraction.html) macro provides the ability to test if two (floating point) values are "close enough".

My initial intention was to test whether the size of the fully-combined file includes all of fragments from the M fragments in the N events.  However, I didn't expect that the size of the all_events.hdf5 file would have exactly the sum of the sizes of the individual fragments (because we expect that the HDF5 format will add some overhead to the size), so I couldn't use BOOST_REQUIRE_EQUAL(fully_combined_file_size, EVENT_COUNT * GEOLOC_COUNT * DUMMYDATA_SIZE).

So, I tried BOOST_REQUIRE_CLOSE_FRACTION call instead.  I experimentally determined the overhead added from HDF5 was about 12%, so I set the "fraction" in the BOOST_REQUIRE_CLOSE_FRACTION to 15% (0.15) to give us a little margin of error.

You might say that 15% is a pretty big window for "close enough".  I can't disagree with that, but with EVENT_COUNT set to 5, a missing event would result in a discrepancy of 20%, so that would get noticed.

You might also say that this test is succeptable to changes over time, for example, if the amount of overhead added by HDF5 changes with different versions of the library.  Again, that would be a good point.  My thought is that the benefit of having such a "close enough" test available in our unit tests all the time is worth the cost of someday possibly needing to update that test.

**Comment by adam-abed-abud** [comment]
That is much clearer now, thanks a lot for the detailed answer. Indeed we can keep it like it is now and if in the future the overhead will increase then we modify this test accordingly.

I'm happy to merge. Let's wait if there are comments from Carlos as well.

**Comment by carloschavez** [comment]
Hi Kurt, 
I have only a couple of comments: 
1) I noticed a couple of places where you left  the    `#include <ers/ers.h>`  after removing calls to ERS_ 
 https://github.com/DUNE-DAQ/ddpdemo/blob/759954d4db57b25067ce3e31ebba733dc2afb63d/include/ddpdemo/StorageKey.hpp#L14
https://github.com/DUNE-DAQ/ddpdemo/blob/759954d4db57b25067ce3e31ebba733dc2afb63d/include/ddpdemo/DataStore.hpp#L22

I think we could remove these includes, unless I am missing something.

2) linter conplains that the constructor of KeyedDataBlock  should be using a `const StorageKey &`  as in
 `explicit KeyedDataBlock(const StorageKey &theKey)`    as theKey is only used in the constructor. 

Other than these two points, I am happy to merge .

Thanks,
Carlos

**Comment by bieryAtFnal** [comment]
Carlos, good points.  I've made those changes.
I also added some comments in the HDF5Combiner_test.cxx file to hopefully make the check that Adam asked about more clear.
Please confirm that the changes look reasonable and merge when you are ready.

**Comment by carloschavez** [comment]
Thanks Kurt,
I am going to merge this PR

**Pull request merged**
